### PR TITLE
Added Documentation

### PR DESCRIPTION
**Pull request by polkapolka**

### CODE REVIEW

**Comment by jamesabel** [comment]
Hi! On this:

BUCKET_NAME = f"awsimple-test-bucket-{str(randint(1,100000)).zfill(5)}"

This will create a new bucket name every time run, correct? I don't think we want to create a bunch of new buckets if we run the example multiple times. Alternatively some combination of the user name and computer name could be used if we want to try to do this automatically (of course, that doesn't guarantee uniqueness, but will usually be OK).

**Comment by polkapolka** [comment]
It was a jenky hack. I was also thinking of using a BUCKET_NAME = input() to allow the user to set the Bucket Name interactively.  I just thought it was better than letting people run it and get a duplicate james bucket error.

**Comment by jamesabel** [comment]
OK - I've pushed to this branch with what I think are the things to leave in and leave out.  Could you pull and re-submit the PR?

**Comment by polkapolka** [comment]
Sure. Later tonight probably.

**Comment by polkapolka** [comment]
Updated to remove conflicting files.

**Pull request merged**
